/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhopratico;

import trabalhopratico.DadosJogador;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class TesteTraducao extends javax.swing.JFrame {

    /**
     * Creates new form TesteTraducao
     */
    private DadosJogador jogador;
    private ArrayList<String> palavras = new ArrayList<String>();
    String linha;
    String[] linhaVet;
    String[] traducoesVet; //palavras que tem mais de uma traducao

    public TesteTraducao() {
        initComponents();
            
    }

    public TesteTraducao(DadosJogador jogador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jogador = jogador;
        try {
            lerArq();
        } catch (IOException ex) {
            Logger.getLogger(TesteTraducao.class.getName()).log(Level.SEVERE, null, ex);
        }
        testa();
    }

    public void lerArq() throws FileNotFoundException, IOException { //copia as palavras que o usuario ja viu para o array palavras
        FileReader fr;
        BufferedReader readerfr = null;
        String linha;
        int cont = 0;
        fr = new FileReader("palavras.txt");
        readerfr = new BufferedReader(fr);

        do {
            linha = readerfr.readLine();
            palavras.add(linha);
            cont++;

        } while (linha != null && cont < jogador.getOndeParei());

        for (int i = 0; i < palavras.size(); i++) {
            System.out.println(palavras.get(i) + "\n");
        }

    }

    public void testa() {
        Random gerador = new Random();
        int numeroAleatorio = gerador.nextInt(jogador.getOndeParei()); //vai selecionar uma das palavras que ja foram apresentadas ao usuario
        

        linha = palavras.get(numeroAleatorio);
        linhaVet = linha.split(";");
        
        palavra.setText(linhaVet[1]);

        traducoesVet = linhaVet[3].split(","); //palavras que tem mais de uma traducao
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        palavra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        traducao = new javax.swing.JTextField();
        proximaPalavra = new javax.swing.JButton();
        resposta = new javax.swing.JLabel();
        conferir = new javax.swing.JButton();
        correcao = new javax.swing.JLabel();
        video = new javax.swing.JButton();
        desempenho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        palavra.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        palavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palavra.setText("jLabel1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(traducao);
        jLabel2.setText("Digite a tradução:");
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        proximaPalavra.setText("Proxima Palavra");
        proximaPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximaPalavraActionPerformed(evt);
            }
        });

        resposta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        resposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        conferir.setText("Conferir Palavra");
        conferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferirActionPerformed(evt);
            }
        });

        correcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        video.setText("Menu");
        video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActionPerformed(evt);
            }
        });

        desempenho.setText("Desempenho");
        desempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desempenhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(traducao)
            .addComponent(palavra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(correcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(conferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proximaPalavra)
                .addContainerGap())
            .addComponent(resposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(desempenho, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(video)
                    .addComponent(desempenho))
                .addGap(31, 31, 31)
                .addComponent(palavra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(traducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(correcao, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximaPalavra)
                    .addComponent(conferir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proximaPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximaPalavraActionPerformed
        // TODO add your handling code here:
        resposta.setVisible(false);
        traducao.setText("");
        correcao.setText(" ");
        testa();
    }//GEN-LAST:event_proximaPalavraActionPerformed

    private void videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActionPerformed
        new Menu().setVisible(true);
        setVisible(false);
        mudarPosicao();
    }//GEN-LAST:event_videoActionPerformed

    private void conferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferirActionPerformed
        // TODO add your handling code here:
        String resp = traducao.getText();
        int aux = 0;
        System.out.println(resp + "\n");

        for (int i = 0; i < traducoesVet.length; i++) { //percorre as traducoes e confere se o usuario digitou alguma das traducoes
            if (resp.compareToIgnoreCase(traducoesVet[i]) == 0) {
                ImageIcon icon = new ImageIcon(getClass().getResource("v.png"));
                resposta.setIcon(icon);
                resposta.setText("Rsposta correta");
                resposta.setVisible(true);
                jogador.setPontos(jogador.getPontos() + 5);
                aux = 1;
                break;
            }
        }
        if (aux == 0) {
            ImageIcon icon = new ImageIcon(getClass().getResource("x.png"));
            resposta.setIcon(icon);
            resposta.setText("Resposta incorreta");
            resposta.setVisible(true);
            correcao.setText("A tradução correta é:" + linhaVet[3]);

        }

    }//GEN-LAST:event_conferirActionPerformed

    private void desempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desempenhoActionPerformed
        mudarPosicao();
        new Desempenho(jogador).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_desempenhoActionPerformed

    public void mudarPosicao() {
        FileReader fr;
        BufferedReader readerf = null;//ler arquivo
        ArrayList<DadosJogador> dado = new ArrayList<>();
        FileWriter fw;
        BufferedWriter fwriter = null;//escrever no arquivo

        try {
            fr = new FileReader("Cadastro.txt");
            readerf = new BufferedReader(fr);
            String linha = readerf.readLine();

            while (linha != null) {//se linha igual a null      todas linhas jÃƒÂ¡ foram lidas
                String[] textoSeparado = linha.split(";");
                DadosJogador d = new DadosJogador();
                d.setNome(textoSeparado[0]);
                d.setSenha(textoSeparado[1]);
                int pontos = Integer.parseInt(textoSeparado[2]);
                int posicao = Integer.parseInt(textoSeparado[3]);
                d.setPontos(pontos);
                d.setOndeParei(posicao);
                if (linha.equals(jogador.getNome() + ";" + jogador.getSenha() + ";" + pontos + ";" + posicao)) {

                    d.setPontos(pontos + jogador.getPontos());
                    d.setOndeParei(jogador.getOndeParei());
                }
                dado.add(d);
                linha = readerf.readLine();
            }

        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);

        } finally {
            if (readerf != null) {
                try {
                    readerf.close();

                } catch (IOException ex) {
                    Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            File file = new File("Cadastro.txt");
            file.delete();
            try {
                fw = new FileWriter("Cadastro.txt", true);
                fwriter = new BufferedWriter(fw);
                for (int i = 0; i < dado.size(); i++) {
                    fwriter.write(dado.get(i).getNome() + ";" + dado.get(i).getSenha() + ";" + dado.get(i).getPontos() + ";" + dado.get(i).getOndeParei() + "\r\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(Editar.class.getName()).log(Level.SEVERE, null, ex);
            } finally {

                try {
                    fwriter.close();

                } catch (IOException ex) {
                    Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteTraducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteTraducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteTraducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteTraducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteTraducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conferir;
    private javax.swing.JLabel correcao;
    private javax.swing.JButton desempenho;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel palavra;
    private javax.swing.JButton proximaPalavra;
    private javax.swing.JLabel resposta;
    private javax.swing.JTextField traducao;
    private javax.swing.JButton video;
    // End of variables declaration//GEN-END:variables
}
